FROM python:3.12-slim

RUN pip install pipenv && \
  apt-get update && \
  apt-get install -y --no-install-recommends wget gcc python3-dev libssl-dev

RUN sh -c "$(wget --output-document - https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin